### PR TITLE
Add snippets

### PR DESCRIPTION
**Pull request by piotrkubisa**
Convert snippets based on the `snippets/go.json` from the microsoft/vscode-go@fc63f6a4.

Script used to automate parsing templates:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

type Snippet map[string]SnippetConfig

type SnippetConfig struct {
	Prefix      string
	Body        string
	Description string
}

var tpl = template.Must(template.New("tpl").Parse(`<snippet>
	<content><![CDATA[
{{.Body}}
]]></content>
	<tabTrigger>{{.Prefix}}</tabTrigger>
	<scope>source.go</scope>
	<description>{{.Description}}</description>
</snippet>
`))

func main() {
	f, err := os.Open("snippets/go.json")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	conf := map[string]Snippet{}
	if err := json.NewDecoder(f).Decode(&conf); err != nil {
		log.Fatal(err)
	}

	for k, v := range conf[".source.go"] {
		normalizedName := strings.ToLower(
			strings.ReplaceAll(
				strings.ReplaceAll(
					strings.ReplaceAll(k, "*", "_"),
					".", "_"),
				" ", "_",
			),
		)
		switch normalizedName {
		case "if_err_!=_nil":
			normalizedName = "if_err_not_nil"
		case "make(___)":
			normalizedName = "make"
		case "new(___)":
			normalizedName = "new"
		case "panic(___)":
			normalizedName = "panic"
		}

		o, err := os.Create(fmt.Sprintf(
			"snippets/out/%s.sublime-snippet", normalizedName,
		))
		if err != nil {
			log.Fatal(err)
		}

		tpl.Execute(o, v)

		o.Close()
	}
}
```

### CODE REVIEW

**Comment by yields** [comment]
Impressive stuff man!

With that said, I'm kinda wondering if snippets are outside of this package scope, I'm 99% sure everyone has their own set of snippets.

Speaking for myself here, but since I have my own snippets and there's no way to disable these snippets they might cause problems, I'm ok with adding them if there's a way to disable them.

What do you think?

**Comment by piotrkubisa** [comment]
How about moving `yields/sublime-go` to new org (let's say `sublime-go`), where we will separate snippets from the `sublime-go` itself? To be honest, I am also a bit concerned about snippets which are included with some package.

**Comment by yields** [comment]
yeah for sure, I think you could publish it as `snippets-go` or something and then I'll link to it from the readme, same for keybindings etc.. I find them annoying sometimes haha

**Comment by piotrkubisa** [comment]
> I'm ok with adding them if there's a way to disable them

Just for FYI: In ST4 (build 4053) currently there is a new setting that makes it possible to disable specific or via wildcard snippet, e.g.:

```json
   "ignored_snippets":
    [
        "PHP/Snippets/$_*",
        "PHP/Snippets/new-array*"
    ],
```

**Comment by piotrkubisa** [comment]
FYI: I added all snippets I have converted into https://github.com/piotrkubisa/sublime-go-snippets

**Pull request closed without merging**
